/laserscan_map:
  ros__parameters:
    pointcloud_topic_name: /rain/autonomous_ship/ndt_filtered_pointcloud
    map_angle_range:
    - -180
    - 180
    map_laser_range:
    - 0.0
    - 200.0
    laserscan_angle_increment: 0.1
    map_vertical_fov_range:
    - -30
    - 30
    visualize_frame: ndt_map
  
  



    
    
