/pointcloud_processor:
  ros__parameters:
    max_num_points : 16 # PointPillars에서 한 Pillars에 들어가는 Point의 개수 
    max_num_pillars: 10000 # Pillar의 최대 개수 -> onnx -> TensorRT로 바꾸는 과정에서 선택한 maxShape의 수를 따라가는 것을 권장
    marker_queue_size : 100 # dbscan에서 사용될 marker의 저장 용량
    dbscan_eps : 1.0
    dbscan_min_samples : 3
    dbscan_tracking_queue_distance : 2.0 # marker_queue와 tracking_queue 간의 식별 과정을 위한 distance
    dbscan_update_tracking_queue_weight : 0.1 # marker_queue가 tracking_queue를 업데이트 시킬 때 tracking_queue가 기존 정보를 얼마나 남길 것인지
    pcd_limit_range: # 입력될 pointcloud의 x1,y1,z1,x2,y2,z2 범위
    - -69.12
    - -69.12
    - -3.0
    - 69.12
    - 69.12
    - 5.0
    voxel_size: # Pillar의 크기
    - 0.32
    - 0.32
    - 8.0
    pointcloud_topic: /filtered_pointcloud # PointPillars Model에 들어가는 Pointcloud2 topic name
    trt_engine: /home/rain/PointPillars/pretrained/model_repvgg_300.trt # TensorRT engine path
    use_sim_time: false

